[project]
name = "speech-to-text-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ffmpeg>=1.4",
    "openai-whisper>=20240930",
    "yt-dlp>=2025.2.19",
]
